### ISSUE TITLE
Missing LICENSE

### ISSUE THREAD

**Issue by Moiman** [rust-av/flavors#13]

**Comment by sdroege** [comment]
@Geal @GuillaumeGomez @Luni-4 You three and me are the only contributors to this repo. So let's agree on a license here? :)

I'd vote for MIT-only, or the usual MIT+Apache2 combination if someone prefers that.

**Comment by GuillaumeGomez** [comment]
MIT-only or MIT+Apache2 are fine by me.

**Comment by Luni-4** [comment]
Same as @GuillaumeGomez, thanks @sdroege! :)

**Comment by Geal** [comment]
both options are fine for me too

**Comment by sdroege** [comment]
Let's go MIT then

**Comment by sdroege** [comment]
See
